import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import Header from "./components/Header";
import { UserProvider } from "@/hooks/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <UserProvider>
          <Toaster
            position="top-right"
            toastOptions={{
              style: {
                background: '#1e293b', // dark blue-gray
                color: '#fff',
                // fontWeight: 'bold', // Remove bold text
              },
              success: {
                style: {
                  background: '#22c55e', // green
                  color: '#fff',
                },
              },
              error: {
                style: {
                  background: '#ef4444', // red
                  color: '#fff',
                },
              },
            }}
          />
          <Header />
          <main className="flex-1 flex items-center justify-center bg-gradient-to-br from-blue-50 to-blue-100">
            {children}
          </main>
        </UserProvider>
      </body>
    </html>
  );
}
